[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit Fingerprint Sensor Library@^2.1.2
    adafruit/Adafruit BusIO@^1.16.1
board_build.flash_mode = dout